version: '3'

vars:
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yml"

  ENV: '{{default "dev" .ENV}}'
  ENV_FILE: '{{printf "%s/.env.%s" .DC_DIR .ENV}}'

  DC_INFRA_ARGS: '--env-file {{.ENV_FILE}} -f {{.INFRA_DC_FILE}}'
  DC_ALL_ARGS:   '--env-file {{.ENV_FILE}} -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}}'

  # ✅ stable compose project name => stable volumes (core-api_loki_data, core-api_postgres_data, etc.)
  COMPOSE_PROJECT_NAME: '{{default "core-api" .COMPOSE_PROJECT_NAME}}'

tasks:
  default:
    cmds:
      - task: ps

  setup_dirs:
    cmds:
      - |
        set -e
        echo "==> Setup Loki storage"

        # (optional) keep folder for bind-mount scenarios
        sudo mkdir -p deployment/docker-compose/loki || true
        sudo chown -R 10001:10001 deployment/docker-compose/loki || true
        sudo chmod -R u+rwX deployment/docker-compose/loki || true

        # ✅ fix named volume perms used by: loki_data:/loki
        LOKI_VOL="{{.COMPOSE_PROJECT_NAME}}_loki_data"
        echo "==> Fix Loki named-volume permissions: $LOKI_VOL"

        docker volume inspect "$LOKI_VOL" >/dev/null 2>&1 || docker volume create "$LOKI_VOL" >/dev/null

        docker run --rm -u 0:0 -v "$LOKI_VOL":/loki alpine:3.19 sh -lc '
          mkdir -p /loki/index /loki/chunks /loki/wal /loki/compactor /loki/cache
          chown -R 10001:10001 /loki
          chmod -R u+rwX /loki
        '

  start_infra:
    deps: [setup_dirs]
    cmds:
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_INFRA_ARGS}} up -d

  stop_infra:
    cmds:
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_INFRA_ARGS}} stop
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_INFRA_ARGS}} rm -f

  pull:
    desc: "Pull latest images"
    cmds:
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} pull

  start:
    desc: "Start all services"
    deps: [setup_dirs]
    cmds:
      - echo "ENV={{.ENV}} COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}}"
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} pull
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} up -d --force-recreate

  stop:
    cmds:
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} stop
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} rm -f

  restart:
    cmds:
      - task: stop
      - task: start

  restart_service:
    desc: "Restart one service. SERVICE=name"
    vars:
      SERVICE: '{{.SERVICE}}'
    cmds:
      - |
        [ -n "{{.SERVICE}}" ] || { echo "Provide SERVICE=name"; exit 1; }
        COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} pull {{.SERVICE}}
        COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} up -d --force-recreate {{.SERVICE}}

  logs:
    vars:
      SERVICE: '{{.SERVICE}}'
    cmds:
      - |
        [ -n "{{.SERVICE}}" ] || { echo "Provide SERVICE=name"; exit 1; }
        COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} logs -f {{.SERVICE}}

  ps:
    cmds:
      - COMPOSE_PROJECT_NAME={{.COMPOSE_PROJECT_NAME}} docker compose {{.DC_ALL_ARGS}} ps

  prune:
    cmds:
      - docker image prune -f
      - docker builder prune -f
      - docker volume prune -f
