version: '3'

vars:
  COMPOSE_PROJECT_NAME: '{{default "core-api" .COMPOSE_PROJECT_NAME}}'
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"
  APPS_DC_FILE: "{{.DC_DIR}}/apps.yml"

  ENV: '{{default "dev" .ENV}}'
  ENV_FILE: '{{printf "%s/.env.%s" .DC_DIR .ENV}}'

  DC_INFRA_ARGS: '--env-file {{.ENV_FILE}} -f {{.INFRA_DC_FILE}}'
  DC_ALL_ARGS:   '--env-file {{.ENV_FILE}} -f {{.INFRA_DC_FILE}} -f {{.APPS_DC_FILE}}'

tasks:

  default:
    cmds:
      - task: ps

  # -------------------------
  # Infra
  # -------------------------

  setup_dirs:
    cmds:
      - |
        set -e

        echo "==> Setup Loki storage"

        # If you are bind-mounting ./loki -> /loki (old method), keep folder ready
        sudo mkdir -p deployment/docker-compose/loki || true
        sudo chown -R 10001:10001 deployment/docker-compose/loki || true
        sudo chmod -R u+rwX deployment/docker-compose/loki || true

        # ✅ If you are using named volume loki_data:/loki (current method), fix volume perms
        # Compose will create it as <project>_loki_data. Default project name usually equals folder name.
        # You can override with: COMPOSE_PROJECT_NAME=core-api
        PROJECT="${COMPOSE_PROJECT_NAME:-$(basename "$PWD")}"
        LOKI_VOL="${PROJECT}_loki_data"

        echo "==> Fix Loki named-volume permissions: $LOKI_VOL"
        docker volume inspect "$LOKI_VOL" >/dev/null 2>&1 || docker volume create "$LOKI_VOL" >/dev/null

        docker run --rm -u 0:0 -v "$LOKI_VOL":/loki alpine:3.19 sh -lc '
          mkdir -p /loki/index /loki/chunks /loki/wal /loki/compactor /loki/cache
          chown -R 10001:10001 /loki
          chmod -R u+rwX /loki
        '


  start_infra:
    deps: [setup_dirs]
    cmds:
      - docker compose {{.DC_INFRA_ARGS}} up -d

  stop_infra:
    cmds:
      - docker compose {{.DC_INFRA_ARGS}} stop
      - docker compose {{.DC_INFRA_ARGS}} rm -f

  # -------------------------
  # Apps
  # -------------------------

  pull:
    desc: "Pull latest images"
    cmds:
      - docker compose {{.DC_ALL_ARGS}} pull

  start:
    desc: "Start all services"
    deps: [setup_dirs]
    cmds:
      - echo "ENV={{.ENV}}"
      - docker compose {{.DC_ALL_ARGS}} pull
      - docker compose {{.DC_ALL_ARGS}} up -d --force-recreate

  stop:
    cmds:
      - docker compose {{.DC_ALL_ARGS}} stop
      - docker compose {{.DC_ALL_ARGS}} rm -f

  restart:
    cmds:
      - task: stop
      - task: start

  # -------------------------
  # Service Controls
  # -------------------------

  restart_service:
    desc: "Restart one service. SERVICE=name"
    vars:
      SERVICE: '{{.SERVICE}}'
    cmds:
      - |
        [ -n "{{.SERVICE}}" ] || { echo "Provide SERVICE=name"; exit 1; }
        docker compose {{.DC_ALL_ARGS}} pull {{.SERVICE}}
        docker compose {{.DC_ALL_ARGS}} up -d --force-recreate {{.SERVICE}}

  logs:
    vars:
      SERVICE: '{{.SERVICE}}'
    cmds:
      - |
        [ -n "{{.SERVICE}}" ] || { echo "Provide SERVICE=name"; exit 1; }
        docker compose {{.DC_ALL_ARGS}} logs -f {{.SERVICE}}

  ps:
    cmds:
      - docker compose {{.DC_ALL_ARGS}} ps

  # -------------------------
  # Cleanup
  # -------------------------

  prune:
    cmds:
      - docker image prune -f
      - docker builder prune -f
      - docker volume prune -f
